# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 06:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('min_team_size', models.IntegerField(default=0)),
                ('max_team_size', models.IntegerField(default=2)),
                ('description', models.TextField()),
                ('prize_1', models.IntegerField(default=0)),
                ('prize_2', models.IntegerField(default=0)),
                ('prize_3', models.IntegerField(default=0)),
                ('max_teams', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(default='default', max_length=30, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', to_field='code')),
                ('first_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('second_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
