# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='first_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_first_member', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='team',
            name='second_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_second_member', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
