# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('min_team_size', models.IntegerField(default=0)),
                ('max_team_size', models.IntegerField(default=2)),
                ('description', models.TextField()),
                ('prize_1', models.IntegerField(default=0)),
                ('prize_2', models.IntegerField(default=0)),
                ('prize_3', models.IntegerField(default=0)),
                ('max_teams', models.IntegerField(default=15)),
            ],
        ),
    ]
