# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160924_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='individual',
            field=models.BooleanField(default=True),
        ),
    ]
