language: python
os:
  - linux
before_install:
  - nvm install 6.3
  - nvm use 6.3
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - npm install
script:
  - python manage.py test
  - npm test
notifications:
  slack: ducic:crtpi7vLCyQjZc1DL6kRN6Ys
  email: false

