language: python
os:
  - linux
before_install:
  - nvm install 6.3
  - nvm use 6.3
python:
  - "3.4"
  - "3.5"
script:
  - echo "==> Running Python Tests"
  - python manage.py test
  - echo "==> Running Frontend Tests"
  - npm test
