# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
