# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160905_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('DL', 'Delhi'), ('WB', 'West Bengal'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra')], max_length=2, null=True),
        ),
    ]
