# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160907_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
