# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20160923_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hackerrank', models.CharField(default=None, max_length=30, unique=True)),
                ('data_gist_url', models.URLField(default=None, max_length=100, unique=True)),
            ],
        ),
    ]
