# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20160926_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='data_gist_url',
            field=models.URLField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='hackerrank',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
