# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20160926_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='data_gist_url',
            new_name='data_weave',
        ),
    ]
